steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - my_func
  - --gen2
  # - --memory=512MiB
  - --max-instances=1
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --allow-unauthenticated
  - --runtime=python311
  # --set-env-vars FUNCTION_MEMORY_MB=512m