steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  # デプロイするfunction名
  - my_func
  # - share_content_automatically
  - --region=asia-northeast1
  # 関数のソースコードの場所
  - --source=./content_share
  # ソースコード内に存在する関数名または完全修飾クラス名
  - --entry-point=main

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - pubsub
  - topics
  - publish
  - sample-function-deploy-topic
  - --message
  - "Finish deploying function !!"