steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - my_func
  - --gen2
  - --run-service-account=sssssssssss@sample-project-396701.iam.gserviceaccount.com
  - --memory=256MiB
  - --max-instances=1
  - --region=asia-northeast1
  - --runtime=python311
  - --source=./content_share
  # - --entry-point=main
  - --trigger-http
  # - --allow-unauthenticated
  # - --env GOOGLE_FUNCTION_TARGET=hello_http
  # - --env GOOGLE_FUNCTION_SOURCE=main.py hello_http
  - --set-env-vars="CONSUMER_KEY"="StYgY0UzncyoksRwbQhuyAy9R","CONSUMER_SECRET"="ITU9RJHfnAyhRm5CSrkUCDClqA4RpjKo9KLDCOReqZvtozhoGf","ACCESS_TOKEN"="HWc0o3FETg7K462p8Gq3Oj9S7qMX0bV0p8V4yQB","ACCESS_TOKEN_SECRET"="m27m9i5ngYVdzn8tgbqdGK1G8AE5xpK58rcPWdQGuorvG"