steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  # デプロイするfunction名
  - share_tech_tube_video_to_x
  - --region=asia-northeast1
  # 関数のソースコードの場所
  - --source=.
  # ソースコード内に存在する関数名または完全修飾クラス名
  - --entry-point=main

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - pubsub
  - topics
  - publish
  - function-deploy-topic
  - --message
  - "Finish deploying content share function !!"